on:
#  workflow_dispatch:
  schedule:
    - cron: '27 4,8 * * *'
  push:
    branches: main

name: Fetch Lausanne airport flights data from Open Sky

jobs:
  generate-data:
    name: update data
    runs-on: ubuntu-22.04
    timeout-minutes: 97

    env:
      RENV_PATHS_ROOT: ~/.local/share/renv
      OPENSKY_USR: ${{ secrets.OPENSKY_USR }}
      OPENSKY_PWD: ${{ secrets.OPENSKY_PWD }}

    steps:

    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v2
      with:
        # don't reinstall R
        install-r: true
        # use RStudio's CRAN mirror with precompiled binaries
        use-public-rspm: true
        r-version: ${{ matrix.config.r }}
        http-user-agent: ${{ matrix.config.http-user-agent }}
        
    - uses: r-lib/actions/setup-r-dependencies@v2
      with:
        extra-packages: any::rcmdcheck
        needs: check

    - uses: r-lib/actions/check-r-package@v2
    
    - name: Create and populate .Renviron file
      run: |
        echo usr="$OPENSKY_USR" >> ~/.Renviron
        echo pwd="$OPENSKY_PWD" >> ~/.Renviron     
      shell: bash

    - name: Install libssh-dev for R OpenSkies, libcurl/libssl & magick
      run: |
        sudo sed -i 's/azure\.//' /etc/apt/sources.list
        sudo apt-get update
        sudo apt-get install -y libssh-dev
        sudo apt-get -y install libcurl4-openssl-dev
        sudo apt-get -y install libmagick++-dev 
            
    - name: Restore packages
      shell: Rscript {0}
      run: |
        if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
        renv::restore()
        
    - name: Get data
      run: Rscript -e 'source("R/save_historical_osn.R")'

    - name: Commit results
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add data/*
        git commit -am "GH Actions Open Sky LSGL flights data $(date)" || echo "No changes to commit"
        git push origin master || echo "No changes to commit"
      env:
        REPO_KEY: ${{secrets.GITHUB_TOKEN}}
        username: github-actions
