on:
  schedule:
    - cron: '27 3,8 * * *'
  push:
    branches: main

name: Get Lausanne airport (LSGL) flights data from Open Sky Network

jobs:
  generate-data:
    name: update data
    runs-on: ubuntu-latest
    timeout-minutes: 67

    env:
      RENV_PATHS_ROOT: ~/.local/share/renv
      OPENSKY_USR: ${{ secrets.OPENSKY_USR }}
      OPENSKY_PWD: ${{ secrets.OPENSKY_PWD }}

    steps:

    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v2
      with:
        # don't reinstall R
        install-r: false
        # use RStudio's CRAN mirror with precompiled binaries
        use-public-rspm: true

    - name: Create and populate .Renviron file
      run: |
        echo usr="$OPENSKY_USR" >> ~/.Renviron
        echo pwd="$OPENSKY_PWD" >> ~/.Renviron     
      shell: bash
